export  LANGUAGE="en_US:en"
export LC_ALL="C"
#colors of ls
LS_COLORS="di=34:fi=0:ln=36:pi=5:so=5:bd=5:cd=5:or=31:mi=0:ex=32:*.pdb=91"
export LS_COLORS


### HISTORY SETTINGS ###
export HISTSIZE=10000000000

# Avoid duplicates
export HISTCONTROL=ignoredups:erasedups

# When the shell exits, append to the history file instead of overwriting it, good when working in multiple terminals
shopt -s histappend

# After each command, append to the history file and reread it, good when working in multiple terminals
export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"

# sets extended pattern matching options in the bash shell
# enables !( not-file) in cp, ls etc
shopt -s extglob  


# User specific aliases and functions
alias l='ls -golFb --color=auto'
alias ls='ls -oghFb --color=auto'
alias lt='ls -lFbth --color=auto'
alias ll='ls -laFbh --color=auto'
alias ..="cd .."
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias cd="cd -P"

#queuing:
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

